config/routes.rb
Rails.application.routes.draw do
  resources :phonebooks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phonebook.rb
class Phonebook < ApplicationRecord

  def self.search_phonenumbers(numbers)
    where("number~*?", numbers)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/phonebooks_controller.rb
class PhonebooksController < ApplicationController
  before_action :set_phonebook, only: %i[ show edit update destroy ]

  # GET /phonebooks or /phonebooks.json
  def index
    if params[:query].present?
      @phonebooks = Phonebook.search_phonenumbers(params[:query])
    else
      @phonebooks = Phonebook.all
    end
  end

  # GET /phonebooks/1 or /phonebooks/1.json
  def show
  end

  # GET /phonebooks/new
  def new
    @phonebook = Phonebook.new
  end

  # GET /phonebooks/1/edit
  def edit
  end

  # POST /phonebooks or /phonebooks.json
  def create
    @phonebook = Phonebook.new(phonebook_params)

    respond_to do |format|
      if @phonebook.save
        format.html { redirect_to @phonebook, notice: "Phonebook was successfully created." }
        format.json { render :show, status: :created, location: @phonebook }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phonebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phonebooks/1 or /phonebooks/1.json
  def update
    respond_to do |format|
      if @phonebook.update(phonebook_params)
        format.html { redirect_to @phonebook, notice: "Phonebook was successfully updated." }
        format.json { render :show, status: :ok, location: @phonebook }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phonebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phonebooks/1 or /phonebooks/1.json
  def destroy
    @phonebook.destroy
    respond_to do |format|
      format.html { redirect_to phonebooks_url, notice: "Phonebook was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phonebook
      @phonebook = Phonebook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phonebook_params
      params.require(:phonebook).permit(:number, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phonebooks_helper.rb
module PhonebooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhoneNumber</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/phonebooks/_form.html.erb
<%= form_with(model: phonebook) do |form| %>
  <% if phonebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phonebook.errors.count, "error") %> prohibited this phonebook from being saved:</h2>

      <ul>
        <% phonebook.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phonebooks/edit.html.erb
<h1>Editing Phonebook</h1>

<%= render 'form', phonebook: @phonebook %>

<%= link_to 'Show', @phonebook %> |
<%= link_to 'Back', phonebooks_path %>

app/views/phonebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phonebooks</h1>

<%= form_tag phonebooks_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phonebooks.each do |phonebook| %>
      <tr>
        <td><%= phonebook.number %></td>
        <td><%= phonebook.name %></td>
        <td><%= link_to 'Show', phonebook %></td>
        <td><%= link_to 'Edit', edit_phonebook_path(phonebook) %></td>
        <td><%= link_to 'Destroy', phonebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phonebook', new_phonebook_path %>

app/views/phonebooks/new.html.erb
<h1>New Phonebook</h1>

<%= render 'form', phonebook: @phonebook %>

<%= link_to 'Back', phonebooks_path %>

app/views/phonebooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @phonebook.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @phonebook.name %>
</p>

<%= link_to 'Edit', edit_phonebook_path(@phonebook) %> |
<%= link_to 'Back', phonebooks_path %>